### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabiommendes** [lappis-unb/versalic-bi#1]
# 1.0
* [ ] Refatorar a API do Salic (salic-api)
* [ ] Redesign e usabilidade do frontend
* [ ] Dados agregados + dataviz
* [ ] Estudos de indicadores culturais (metabase ou similares)
* [ ] ML aplicado a inferências automáticas

# Futuro
* [ ] Página personalizada por projeto + QR code?
* [ ] Crowdfunding?
* [ ] Tinder cultural?
